### ISSUE TITLE
SwiftCodeStyle

### ISSUE THREAD

**Issue by saroar** [PerfectExamples/Perfect-APNS-Demo#1]
# like to know why you doing this coding style what plus 

```class NewsItem {
    
    private var _title: String
    private var _description: String
    private var _imageURL: URL?
    
    var title: String {
        get {
            return _title
        }
    }
    
    var description: String {
        get {
            return _description
        }
    }
    
    var imageURL: URL? {
        get {
            return _imageURL
        }
    }
    
    init(title: String, description: String, imageURL: URL?) {
        _title = title
        _description = description
        _imageURL = imageURL
    }
    
}

// why not this
class NewsItem {
    private(set) var title: String
    private(set) var description: String
    private(set) var imageURL: URL?
    
    init(title: String, description: String, imageURL: URL?) {
        self.title = title
        self.description = description
        self.imageURL = imageURL
    }
    
}

// less and clean code

**Comment by rymcol** [comment]
There still needs to be a public accessor, and the `_` makes the private vars easier to read/recognize at quick glance.

**Comment by saroar** [comment]
ok i am not too clear but 

```
class NewsItem {
    private(set) var title: String
    private(set) var description: String
    private(set) var imageURL: URL?
    
    init(title: String, description: String, imageURL: URL?) {
        self.title = title
        self.description = description
        self.imageURL = imageURL
    }
    
}
```

instead of making computed properties, the same effect can be reached with 
`private(set) var imageURL: URL?` etc.
Read-only on the outside, but still writable inside.

this code work for me super and it have  i try already thanks for ur reply :)

**Comment by rymcol** [comment]
To be fair the syntax I used is leftover from a time before `private(set)` existed. Traditionally in iOS the way I did it is how a lot of devs used to. `private(set)` was introduced in a later version of Swift (3.1? or 4?) and either pattern will work just fine.

**Comment by saroar** [comment]
oo I see sorry I just learning that's why I asking lot now clear 
and I am not sure about Swift the version 

but thanks for your quick reply
